In [1]:
import torch

In [22]:
x = torch.randn(3, 5, 4)

# xt.unsqueeze(tuple(range(1, xt.dim())))


In [27]:
xt_indices = torch.arange(x.size(0))
print(xt_indices.shape)
for dim in range(1, x.dim()):
    xt_indices = xt_indices.unsqueeze(dim)

# Expandiere die Indizes auf die gleiche Shape wie das ursprüngliche xt
print(xt_indices.shape)

torch.Size([3])
torch.Size([3, 1, 1])


In [55]:
B, S, N, H, Q, V = 3, 4, 5, 2, 6, 7
x0 = torch.rand(B, S, N)
lst = tuple(range(1, x0.dim()))

x0 = torch.arange(3)
for i in lst:
    x0 = x0.unsqueeze(i)
print(x0.shape)
print(x0)

torch.Size([3, 1, 1])
tensor([[[0]],

        [[1]],

        [[2]]])


In [53]:
import jax
import jax.numpy as jnp

# Beispiel xt mit Shape (B, S, N, H, Q, V)
B, S, N, H, Q, V = 3, 4, 5, 2, 6, 7
xt = jax.random.uniform(jax.random.PRNGKey(0), (B, S, N))
print(type(xt))
print(xt.shape[0])
print(xt)
# Berechne b
torch.arange
b = jnp.expand_dims(jnp.arange(xt.shape[0]), tuple(range(1, xt.ndim)))
print(b.shape)
print((b))

<class 'jaxlib.xla_extension.ArrayImpl'>
3
[[[0.12447917 0.1094259  0.23693919 0.94575596 0.1594727 ]
  [0.84554565 0.01326525 0.37130654 0.34224176 0.6253567 ]
  [0.7081952  0.16291368 0.29458654 0.00194848 0.5491575 ]
  [0.8475604  0.925928   0.54306674 0.40060925 0.8868216 ]]

 [[0.95004666 0.51836514 0.63809705 0.06671274 0.6426624 ]
  [0.31780863 0.21331525 0.2628814  0.25734162 0.72351336]
  [0.062621   0.16465926 0.02687132 0.1529026  0.25560737]
  [0.03544354 0.31713212 0.33358395 0.948547   0.93193233]]

 [[0.73810947 0.20734286 0.13556743 0.57623744 0.05131841]
  [0.8201177  0.5338551  0.8530345  0.96546125 0.9175153 ]
  [0.33442986 0.95699656 0.95403767 0.92046404 0.5596161 ]
  [0.42783093 0.9162421  0.4420396  0.6804645  0.46406043]]]
(3, 1, 1)
[[[0]]

 [[1]]

 [[2]]]


In [64]:
x1 = torch.randn(2, 2)
print(x1, x1.shape)
x2 = torch.tile(x1, (3, 1))
print(x2, x2.shape)

tensor([[ 0.2499,  1.6694],
        [-0.5757, -0.0826]]) torch.Size([2, 2])
tensor([[ 0.2499,  1.6694],
        [-0.5757, -0.0826],
        [ 0.2499,  1.6694],
        [-0.5757, -0.0826],
        [ 0.2499,  1.6694],
        [-0.5757, -0.0826]]) torch.Size([6, 2])


In [81]:
print(jnp.eye(4))
mask = jnp.eye(4).repeat(2, axis=0)
print(mask)
mask0 = torch.eye(4).repeat_interleave(2, 0)
print(mask0)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])


In [121]:
B = 2
S = 2

xt = jax.random.uniform(jax.random.PRNGKey(0), (B, S))
print(xt)
#print(jnp.tile(xt, (2 * 3, 1)).shape)
#print(jnp.tile(jnp.expand_dims(xt, axis=1), ((3, 1))).shape)

print(jnp.reshape(xt, (-1, 4)).T)

x1 = torch.randn(3, 2, 2)
#print(torch.tile(x1.unsqueeze(1), ((3, 1))).shape)
print(x1.view(-1, 4).t())


[[0.9653214  0.22515893]
 [0.63302994 0.29638183]]
[[0.9653214 ]
 [0.22515893]
 [0.63302994]
 [0.29638183]]
tensor([[ 0.0580,  0.2162, -0.8515],
        [-0.8934, -1.4802,  0.6290],
        [-0.3249, -0.1572,  0.0770],
        [-1.3485, -0.0259,  0.0858]])


In [89]:
print(jnp.arange(12).repeat(4, axis=0))
print(torch.arange(12).repeat_interleave(4, 0))

[ 0  0  0  0  1  1  1  1  2  2  2  2  3  3  3  3  4  4  4  4  5  5  5  5
  6  6  6  6  7  7  7  7  8  8  8  8  9  9  9  9 10 10 10 10 11 11 11 11]
tensor([ 0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,
         4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,
         9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11])


In [117]:
bsize = 4
d = 3
s = 2
xt = jax.random.uniform(jax.random.PRNGKey(0), (B, S))
print(xt)
print(jnp.repeat(jnp.arange(bsize), d * s))
print(jnp.repeat(jnp.ravel(xt), s))
print(jnp.tile(jnp.arange(4), [bsize * d]))
print('--------------------')
print(x1)
print(torch.arange(bsize).repeat_interleave(d * s))
print(torch.flatten(x1).repeat_interleave(s))
print(torch.tile(torch.arange(4), [bsize * d]))




[[0.9653214  0.22515893]
 [0.63302994 0.29638183]]
[0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3]
[0.9653214  0.9653214  0.22515893 0.22515893 0.63302994 0.63302994
 0.29638183 0.29638183]
[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0
 1 2 3 0 1 2 3 0 1 2 3]
--------------------
tensor([[-0.9290,  0.0699],
        [-0.5814, -0.2196]])
tensor([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3])
tensor([-0.9290, -0.9290,  0.0699,  0.0699, -0.5814, -0.5814, -0.2196, -0.2196])
tensor([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3,
        0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])


In [123]:
#print(torch.zeros([2, 3] + [3, 4], dtype=torch.float32))
print(torch.split(x, [1], dim=1))

RuntimeError: split_with_sizes expects split_sizes to sum exactly to 5 (input tensor's size at dimension 1), but got split_sizes=[1]

In [4]:
import torch
bsize = 3
print(torch.rand(bsize, ))

tensor([0.2168, 0.5465, 0.4740])
